from time import sleep

print("This is TerraBot. Please enter your current location to start the T.A.R.D.I.S system.")
clocation = input()
print("PROCESSING...")
sleep(1)
print("Hello, unidentified_user. Your current location is " + clocation + ", the time is 12:34, and the weather is: slightly cloudy with a chance of hail.")
sleep(3)
print("Starting Tardis systems. Please wait a few seconds for all of the systems to start up. Bye! -TerraBot.")
print("RUNNING 'LOADTARDIS.EXE'; PLEASE DO NOT SHUT OFF THE TARDIS MACHINE.")
sleep(6)
print("ACTIVATING ALL SAFETY PROTOCOLS...")
sleep(2)
print("56%")
sleep(0.45)
print("68%")
sleep(4)
print("100%")
sleep(1)
print("STARTING ALL SYSTEMS...")
sleep(5)
print("78%")
sleep(0.87)
print("80%")
sleep(2)
print("86%")
sleep(3)
print("97.2%")
sleep(4)
print("100%")
print("LOAD SUCCESSFUL. STARTING UP...")
sleep(7)
print("HELLO.")
print("WELCOME TO THE TARDIS. PLEASE PRESS 'xyzxx12dc' ON YOUR KEYBOARD AND HIT ENER TO OPEN HATCH AND SCAN YOUR CREW KEY (TARDIS TM.)")
scankey = input()
if scankey == "xyzxx12dc":
    print("SCANNING: 25% COMPLETE")
    sleep(3)
    print("SCANNING: 67% COMPLETE")
    sleep(2)
    print("SCANNING: 79% COMPLETE")
    sleep(4)
    print("SCANNING: 99% COMPLETE")
    sleep(7)
    print("SCANNING: 100% COMPLETE")
    sleep(1)
    print("GOOD TO SEE YOU, USER12144")
    print("WE HAVE NOTICED THAT YOU DO NOT HAVE A USER NAME. PLEASE ENTER YOUR NEW NAME AND HIT ENTER.")
    username = input()
    print("PROCESSING. PLEASE WAIT...")
    sleep(5)
    print("HOW ARE YOU LIKING YOUR NEW NAME," + username + "?")
    print("NOW THAT YOU HAVE SIGNED IN TO THE TARDIS DATABASE, WORLD12-44 EXCLUSIVE, PLEASE TELL US WHERE YOU WOULD LIKE TO GO.")
    print("LIST OF OPTIONS: 1: BACKROOMS - ASYNC INC. 2: PLANET E-456, NEBULA B3, 3: PLANET EARTH-X, CLUSTER II, LACTOSE WAY, 4: HOMEBASE, GALACTIX 55-6")
    print(" #1 = b #2 = e-456 #3 = e-x #4 = hb")
    goto = input()
    if goto == "b":
        print("TURNING ON BOOSTERS. CALCULATING DESTINATION. PREPARING EMERGENCY EXITS. PLEASE PUT ON YOUR ASYNC HASMAT SUITS, AS THIS IS A HIGHLY CONTAMINATED ZONE, FULL OF BACTERIA AND VIRUSES. BRING PROPER SAFETY EQUIPMENT, LIKE ITEMS TO REPEAR BROKEN HASMAT SUITS, SUIT CAMS AND FLAMETHROWERS.")
        print("RED WIRE TO FIND YOUR WAY BACK TO THE LAB WILL BE GIVEN TO YOU WHEN YOU GET THERE. KEEP AN EYE OUT FOR THE MUTATED BACTERIA AND DRINKABLE ALMOND WATER.")
        sleep(15)
        print("ACTIVATING CLEAROGEL. CHEKCING COOLANT SYSTEMS. STIMULATING ION DETANATION FROM FUEL CRYSTALS. FILLING FUEL TANKS. FILLING OXYGEN TANKS.")
        sleep(10)
        print("PLEASE HOLD ONTO YOUR SEATS AND PUT ON THE SAFETY STRAP. WE WILL LEAVE IN:")
        print("5...")
        sleep(2)
        print("4...")
        sleep(2)
        print("3...")
        sleep(2)
        print("2...")
        sleep(2)
        print("1...")
        sleep(3)
        print("BLAST OFF! TIME UNTIL DESTINATION REACH: 10 SECONDS.")
        sleep(5)
        print("HALFWAY.")
        sleep(5)
        print("ACTIVATING BRAKES. EJECTING FUEL CRYSTALS. RELEASING BRAKE BOOSTERS. PLEASE WAIT ANOTHER 10 SECONDS TO SAFELY LAND, WHEN WE HAVE LOST ALL FRICTION.")
        sleep(10)
        print("SUCCESSFUL LANDING. PLEASE EXIT NOW. TYPE 'goodbye_tardis' TO SHUT DOWN TARDIS. DEACTIVATING UN-NECESARY SYSTEMS TO PRESERVE POWER.")
        print("TYPE 'goback_initiate' ON YOUR KEYBOARD TO RE-START ALL SYSTEMS AND GO BACK TO YOUR HOME.")
        whatnext = input()
        if whatnext == "goback_initiate":
            print("ACTIVATING QUICK-TRAVEL V.91")
            print("PLEASE PUT ON YOUR GAS MASKS ABOVE YOUR HEADS TO BE ABLE TO BREATH DURING THE TRIP AS WE WILL BE GOING SO FAST OXYGEN WILL NOT BE ABLE TO MANUALLY ENTER YOUR LUNGS")
            print("ACTIVATING INTER DIMENSIONAL PORTAL. QUICK TRAVELING IN:")
            sleep(3)
            print("'TAKE OFF TIME' SYSTEMS FAILED. PREPARE TO LAUNCH AT ANY MOMENT.")
            sleep(4)
            print("BOOM! WE HAVE ENTERED QUICK TRAVEL. EXITING IN 3 SECONDS")
            sleep(3)
            print("BRACE FOR IMPACT. BANG. WE HAVE LANDED. READINGS SHOW THAT THE LANDING WHEELS SUSTAINED MINOR DAMAGE. FIXING NOW. YOU MAY EXIT THE TARDIS.")
        if whatnext == "goodbye_tardis":
            print("SHUTTING DOWN ALL SYSTEMS. ACTIVATING INVISIBLE CAMOFLAUGE. GOODBYE, " + username + "!")
    if goto == "e-456":
        print("PLANET 'e-456' IS LIKE AN ALTERNATE VERSION OF OUR UNIVERSE. IT IS LOCATED IN 'Nebula B3', AND WAS COLONISED DUE TO BEING VERY SIMILAR TO OUR PLANET. THE PLACE CONSISTS OF A MOSTLY OXYGENATED ATMOSPHERE, WITH A SWEET, SALTY LIQUID THAT MAKES UP THE SEAS CALLED, 'Liquid-42'. HOW THIS LIQUID WAS FORMED IS UNKNOWN, BUT IT IS SAFE TO DRINK.")
        sleep(21)
        print("DO NOT APROACH ANY WILDIFE THERE WHEN UNSUPERVISED, AS MOST OF THE ANIMALS, PLANTS, FUNGI HERE ARE DANGEROUS.")
        sleep(6)
        print("TURNING ON BOOSTERS. CALCULATING DESTINATION. PREPARING EMERGENCY EXITS.")
        sleep(6)
        print("ACTIVATING CLEAROGEL. CHEKCING COOLANT SYSTEMS. STIMULATING ION DETANATION FROM FUEL CRYSTALS. FILLING FUEL TANKS. FILLING OXYGEN TANKS.")
        sleep(10)
        print("PLEASE HOLD ONTO YOUR SEATS AND PUT ON THE SAFETY STRAP. WE WILL LEAVE IN:")
        print("5...")
        sleep(2)
        print("4...")
        sleep(2)
        print("3...")
        sleep(2)
        print("2...")
        sleep(2)
        print("1...")
        sleep(3)
        print("BLAST OFF! TIME UNTIL DESTINATION REACH: 10 SECONDS.")
        sleep(5)
        print("HALFWAY.")
        sleep(5)
        print("ACTIVATING BRAKES. EJECTING FUEL CRYSTALS. RELEASING BRAKE BOOSTERS. PLEASE WAIT ANOTHER 10 SECONDS TO SAFELY LAND, WHEN WE HAVE LOST ALL FRICTION.")
        sleep(10)
        print("SUCCESSFUL LANDING. PLEASE EXIT NOW. TYPE 'goodbye_tardis' TO SHUT DOWN TARDIS. DEACTIVATING UN-NECESARY SYSTEMS TO PRESERVE POWER.")
        print("TYPE 'goback_initiate' ON YOUR KEYBOARD TO RE-START ALL SYSTEMS AND GO BACK TO YOUR HOME.")
        whatnext = input()
        if whatnext == "goback_initiate":
            print("ACTIVATING QUICK-TRAVEL V.91")
            print("PLEASE PUT ON YOUR GAS MASKS ABOVE YOUR HEADS TO BE ABLE TO BREATH DURING THE TRIP AS WE WILL BE GOING SO FAST OXYGEN WILL NOT BE ABLE TO MANUALLY ENTER YOUR LUNGS")
            print("ACTIVATING INTER DIMENSIONAL PORTAL. QUICK TRAVELING IN:")
            sleep(3)
            print("'TAKE OFF TIME' SYSTEMS FAILED. PREPARE TO LAUNCH AT ANY MOMENT.")
            sleep(4)
            print("BOOM! WE HAVE ENTERED QUICK TRAVEL. EXITING IN 3 SECONDS")
            sleep(3)
            print("BRACE FOR IMPACT. BANG. WE HAVE LANDED. READINGS SHOW THAT THE LANDING WHEELS SUSTAINED MINOR DAMAGE. FIXING NOW. YOU MAY EXIT THE TARDIS.")
        if whatnext == "goodbye_tardis":
            print("SHUTTING DOWN ALL SYSTEMS. ACTIVATING INVISIBLE CAMOFLAUGE. GOODBYE, " + username + "!")
    if goto == "e-x":
        print("EARTHERIA XENOVIA 46, MORE COMMONLY KNOWN AS EARTH-X, IS A WASTELAND, WITH A HIGHLY TOXIC ATMOSPHERE, ACID RAIN, HIGH PRESSURE, EQUIVALENT TO SWIMMING A FEW MILES UNDERWATER, AND A BAREN, ROCKY LANDSCAPE. THE ONLY GOOD THING ABOUT THIS PLANET IS HOW MINERAL RICH IT IS.")
        print("DUE TO THE CONDITIONS OF THE PLANET, WHEN EXITING THE TARDIS, YOU MUST WEAR A HIGHLY PROTECTIVE, CLASS 18 M.U.C EXTREME ENVIRONMENT SUIT (C18_M.U.C_E.E.S)")
        print("WHEN LANDED, THE TARDIS WILL NOT SHUT OFF, AS IF THE SYSTEMS ARE DISABLED, THE OUTER LAYER OF THE SHIP WOULD MELT, LEAVING THE FRAGILE PARTS EXPOSED. THERE WILL BE NO BREATHABLE AIR HERE, SO BE WEARY. WHEN YOU EXIT THE TARDIS, RUN AS FAST AS YOU CAN, AS GOING SLOWLY WILL DAMAGE THE SUIT FROM THE CONDITIONS.")
        print("PLEASE DO NOT EXIT THE BASES THAT YOU WILL ENTER WHEN YOU LAND ON THIS WORLD, AS YOU WILL EASILY BE DECIMATED BY THE WEATHER. GOOD LUCK!")
        sleep(55)
        print("TURNING ON BOOSTERS. CALCULATING DESTINATION. PREPARING EMERGENCY EXITS.")
        sleep(2)
        print("ACTIVATING CLEAROGEL. CHEKCING COOLANT SYSTEMS. STIMULATING ION DETANATION FROM FUEL CRYSTALS. FILLING FUEL TANKS. FILLING OXYGEN TANKS.")
        sleep(10)
        print("PLEASE HOLD ONTO YOUR SEATS AND PUT ON THE SAFETY STRAP. WE WILL LEAVE IN:")
        print("5...")
        sleep(2)
        print("4...")
        sleep(2)
        print("3...")
        sleep(2)
        print("2...")
        sleep(2)
        print("1...")
        sleep(3)
        print("BLAST OFF! TIME UNTIL DESTINATION REACH: 10 SECONDS.")
        sleep(5)
        print("HALFWAY.")
        sleep(10)
        print("DETECTING THREAT... PLEASE WAIT. SCANNING...")
        sleep(3)
        print("IDENTIFYING THREAT:")
        print("PREFORMING RADIOWAVE SCAN...")
        sleep(4)
        print("idinfijsndiusdnfincisiunin12uinuiniudnisuncnijdncisdncishbcubsiuysudygbugbubSDSEFDVDVJDSD__BESFHNSDHFIDNIUDIAWHD-NJDNIUNDASJN-DLNDIAJSDN-AJSNDKAJSDNAKJSDNISFNIMUWU12354dgchnchdndhdhdhgfbcgfmjlkpolkpollaolpoldlpoasewrgdg11nnnbjn2hh3hhdhnchsdshnjsnjchsncjhbscjhsncjsjfjfueuehudhcidjhijii-456796869724352jdjjdjdfnccnnindiwnjnuhbbihiuiuhiuhiygfgadgnjdcdmcoscosmcos________bhbhbh12bhbuhbucnu89nxndcuncusncusncusncusncbhn46bhbcjhdjhbsjhbhbcnejkdjnkdjncjdnccnnxbshishuhcuhhdnicjncincjnjnjnjnhhysbgsbdghnjdnd000990099999900990010100000111100020002ijijj-7-8-6-7-8-9-ujijidhshbuabduyasduyhsudy'#~~~~///////????!##~~~~hdusiudh~##############123jdsujdsu45dhhnhnc76uhsduhsd8jjj0")
        sleep(1)
        print("udhushduhsudhsjdna#udyhaudyhasuydhsuydhayushday--- #12366 LOCATED.")
        sleep(2)
        print("RADIOWAVE SCAN COMPLETE.")
        print("THREAT IDENTIFIED.")
        print("PLEASE EXIT TO YOUR LIFE PODS, AS AN UNKNOW SPECIES HAS ENTERED THE SHIP.")
        sleep(5)
        print("*WARNING* *WARNING* AN ALIEN SPECIES HAS ENTERED THE SHIP- PLEASE EVACUATE TO THE LIFE PODS LOCATED ON HALLWAY 678, 899, 432, 106. THIS MESSAGE WILL NOW REPEAT!")
        sleep(2)
        print("*WARNING* *WARNING* AN ALIEN SPECIES HAS ENTERED THE SHIP- PLEASE EVACUATE TO THE LIFE PODS LOCATED ON HALLWAY 678, 899, 432, 106. THIS MESSAGE WILL NOW REPEAT!")
        sleep(2)
        print("*WARNING* *WARNING* AN ALIEN SPECIES HAS ENTERED THE SHIP- PLEASE EVACUATE TO THE LIFE PODS LOCATED ON HALLWAY 678, 899, 432, 106. THIS MESSAGE WILL NOW REPEAT!")
        sleep(2)
        print("*WARNING* *WARNING* AN ALIEN SPECIES HAS ENTERED THE SHIP- PLEASE EVACUATE TO THE LIFE PODS LOCATED ON HALLWAY 678, 899, 432, 106. THIS MESSAGE WILL NOW REPEAT!")
        sleep(2)
        print("EJECTING LIFE PODS. ACTIVATING DEFENSE SYSTEMS. RELEASING POISONOUS GASSES. ALL CREW, PLEASE PUT ON YOUR GAS MASK AS YOU EVACUATE TO THE LIFE PODS. RUNNING SELF DESTRUCTION PROGRAMME.")
        print("RUNNING:")
        sleep(1)
        print("5%")
        sleep(5)
        print("26%")
        sleep(4)
        print("56%")
        sleep(3)
        print("78%")
        sleep(2)
        print("81%")
        sleep(2)
        print("99.98%")
        sleep(2)
        print("99.99%")
        print("100%")
        print("SELF DESTRUCTION IN 3... 2... 1...")
        sleep(1)
        print("SELF DESTRUCT INITIATED.")
    if goto == "hb":
        print("HOMEBASE IS WHERE YOU LIVE, WHERE TARDISES ARE BUILT, AS WELL AS MARK-45 TARDI, AND WHERE RESEARCH IS DONE ON PLANETS AND GALAXYS, ECT. ONCE AT HOMEBASE YOU HAVE THE OPTION TO TRAVEL TO YOUR HOME PLANET.")
        print("PLEASE HOLD ONTO YOUR SEATS AND PUT ON THE SAFETY STRAP. WE WILL LEAVE IN:")
        print("5...")
        sleep(2)
        print("4...")
        sleep(2)
        print("3...")
        sleep(2)
        print("2...")
        sleep(2)
        print("1...")
        sleep(3)
        print("BLAST OFF! TIME UNTIL DESTINATION REACH: 10 SECONDS.")
        sleep(5)
        print("HALFWAY.")
        sleep(5)
        print("ACTIVATING BRAKES. EJECTING FUEL CRYSTALS. RELEASING BRAKE BOOSTERS. PLEASE WAIT ANOTHER 10 SECONDS TO SAFELY LAND, WHEN WE HAVE LOST ALL FRICTION.")
        sleep(10)
        print("SUCCESSFUL LANDING. PLEASE EXIT NOW! BYE!")
        sleep(2)
        print("SHUTTING DOWN.")
        
    
        

        
            
              
    

